### PR TITLE
use Micronaut version catalogue

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Review by timyates — COMMENTED** [review]
Why only move half the builds to `.kts`?  Want me to do the rest?

**Comment by sdelamo** [comment]
> Why only move half the builds to `.kts`? Want me to do the rest?

If you have cycles please do. I just move the low hanging fruit.

**Comment by sdelamo** [comment]
@timyates please note that we seem not be publishing a 

version catalogue for discovery client. Hence: 

```java
    api("io.micronaut.discovery:micronaut-discovery-client")
```

Please, create a task and added to 3.8.0 project start publish a version catalogue for discovery client.

**Comment by timyates** [comment]
> @timyates please note that we seem not be publishing a
> 
> version catalogue for discovery client. Hence:
> 
> ```java
>     api("io.micronaut.discovery:micronaut-discovery-client")
> ```
> 
> Please, create a task and added to 3.8.0 project start publish a version catalogue for discovery client.

@sdelamo I believe we are, that dependency is called `mn.micronaut.discovery`

Checked in core 3.7.0 and 3.6.3

**Comment by timyates** [comment]
https://github.com/micronaut-projects/micronaut-aws/pull/1454

**Pull request merged**
