### PR TITLE
Reliable Async events on AWS Lambda

### PR DESCRIPTION
**Pull request by musketyr**
This is an implementation of https://github.com/micronaut-projects/micronaut-core/issues/7858 for AWS Lambda

### CODE REVIEW

**Comment by musketyr** [comment]
hi @graemerocher or @sdelamo, is the master branch in a bad shape? the broken tests seems unrelated my code.

**Comment by sdelamo** [comment]
> hi @graemerocher or @sdelamo, is the master branch in a bad shape? the broken tests seems unrelated my code.

We forgot an `@Requires`. https://github.com/micronaut-projects/micronaut-aws/pull/1464

**Comment by sdelamo** [comment]
Closing this. I am not sure this is longer relevant. @musketyr let me know if you think we should resuscitate this.

**Comment by musketyr** [comment]
Feel free to close it. There is a more elegant solution, simply replace the bean handling the `@Async` introduction. I can try to look for a snippet of you're interested.

**Pull request closed without merging**
