### PR TITLE
Update and revise the api gateway example.

### PR DESCRIPTION
**Pull request by kastork**
- gitignore the bin directory, which is a build product directory
- update dependencies
  - micronaut 1.2.2
  - shadowJar plugin
  - logging dependencies
- Utilize the gradle 5.x BOM system instead of the spring dependency management plugin
- Deploy the fat jar instead of a zip file
- Make a version of the sam file that supports local development without a re-invocation of SAM Local for every code change
- Get logging to Cloud Watch working

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks! could you sign the CLA?

**Comment by kastork** [comment]
I've tried to sign more than once, not sure what's going wrong.  Will keep at it.

**Comment by kastork** [comment]
I think I got it.  Email address confusion in my github settings.

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
