### PR TITLE
More details to release process

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by graemerocher** [comment]
@alvarosanchez can confirm but I don't believe those steps are necessary. All you have to do is publish the release from the releases page

**Comment by alvarosanchez** [comment]
Indeed they are not necessary. I will also reverts the commits you manually made since that is handled by the release process

**Comment by graemerocher** [comment]
btw the latest release run failed https://github.com/micronaut-projects/micronaut-aws/actions/runs/68143913 

The docs didn't publish. Seems central sync failed

**Comment by alvarosanchez** [comment]
Yeah, we will undo stuff and retry

**Pull request closed without merging**
