### PR TITLE
Revert "add temporary @Ignore"

### PR DESCRIPTION
**Pull request by sdelamo**
This reverts commit 4bec11676d60471f6aeb20015cfa1ad304f3001d.

### CODE REVIEW

**Comment by sdelamo** [comment]
@timyates can investigate this failure?

**Comment by timyates** [comment]
Blocked by bug in core: https://github.com/micronaut-projects/micronaut-core/issues/9154

**Comment by timyates** [comment]
@sdelamo So this was a bug in core, which denis has now fixed

https://github.com/micronaut-projects/micronaut-core/pull/9155
https://ge.micronaut.io/s/kf3qapojl3jv2/tests/:micronaut-function-client-aws:test/io.micronaut.function.client.aws.AwsLambdaInvokeSpec/test%20setup%20lambda%20config?top-execution=1

The test doesn't run on CI, but locally it will fail until we have an M3 release of core, and we update aws to use it

**Comment by sdelamo** [comment]
can you annotate the failing test with `@PendingFeature` and add `@Issue` with value https://github.com/micronaut-projects/micronaut-core/pull/9155 and we will merge this Pr.

**Pull request merged**
