### PR TITLE
Disable System Manager Parameter Store queries by micronaut environment

### PR DESCRIPTION
**Pull request by sam-lewis**
PR resolves https://github.com/micronaut-projects/micronaut-aws/issues/376

### CODE REVIEW

**Comment by sam-lewis** [comment]
I am not very happy with the test, any suggestions on the best approach to creating `AWSParameterStoreConfigClient` with different configurations in different test scenarios would be appreciated.

Also, I did a tiny but of refactoring but that could be done as a separate MR:
- Correct a logger class
- Remove an unused variable
- Fix javadoc variable substitutions
- Remove semicolons from groovy file

**Comment by graemerocher** [comment]
The tests for this integration are complex yes, suggestions on how we can improve this welcome.

**Comment by sam-lewis** [comment]
Integration tests with [Localstack](https://github.com/localstack/localstack) and [Testcontainers](https://www.testcontainers.org/modules/localstack/) could be nice because the mocking could be removed.
That would have disadvantages though:
- Build dependency on docker
- Much slower tests due to image download and container start-up
Is this something you would consider?

Alternatively a bit of refactoring to extract common methods for mock interactions and a common method to create `AWSParameterStoreConfigClient` with different configuration properties could be an improvement.

**Comment by alvarosanchez** [comment]
@sam-lewis we use Testcontainers in quite a few Micronaut modules, so I don't see any problem using it for some specific tests like this one.

If you are willing to contribute that, go ahead. That said, in my opinion, this PR is good to go. If you agree, we can merge it as is, and have the Localstack+Testcontainers integration in a separate PR. Thoughts?

**Review by alvarosanchez — APPROVED** [review]

**Comment by sam-lewis** [comment]
@alvarosanchez I think that Localstack+Testcontainers integration would be better as a separate PR so it would be good to merge this.

**Pull request merged**
