### PR TITLE
Added reflection metadata to aws-cloudwatch-logging module

### PR DESCRIPTION
**Pull request by msupic**

### CODE REVIEW

**Review by sdelamo — APPROVED** [review]
should this reflection configuration not be in the [GraalVM Metadata repository](https://github.com/oracle/graalvm-reachability-metadata)?

**Comment by msupic** [comment]
@sdelamo - `CloudWatchLoggingAppender` and `CloudWatchJsonFormatter` metadata should be in `micronaut-aws-cloudwatch-logging` since those are micronaut classes. `LayoutWrappingEncoder`, `JsonLayoutBase` and `JsonLayout` metadata are temporarily placed here until the following PRs get approved and new version of metadata repository get released:
```
https://github.com/oracle/graalvm-reachability-metadata/pull/372
https://github.com/oracle/graalvm-reachability-metadata/pull/378
```
Since entire process of adding metadata to the shared repository is extremely slow (can take a few months until PRs are approved, a new release of metadata repository created, a new release of NBT plugin created and then that NBT release used in micronaut gradle and maven plugins), I temporarily added those metadata to micronaut modules. Those metadata will be removed when entire above mentioned process gets completed.

**Comment by sdelamo** [comment]
how are we tracking the things we have to remove when they are in the Metadata repository? Are you creating issues so that we don't forget?

**Comment by msupic** [comment]
It doesn't happen often that I add new metadata which need to be removed later when a new version of NBT plugin is released so I am tracking those cases locally. If you prefer, I can create new issues for those cases?

**Pull request merged**
