### PR TITLE
Fix bom

### PR DESCRIPTION
**Pull request by sdelamo**
@melix 

> @sdelamo Just noticed that the AWS BOM is wrongly generated (I was using this project to try an internal BOM plugin). It contains projects it shouldn't, some groups are wrong and some versions undefined. It's late here so I won't fix it today but we have to fix it before a release.

bom was introduce here: 

https://github.com/micronaut-projects/micronaut-aws/pull/963

### CODE REVIEW

**Comment by sdelamo** [comment]
[I've excluded the `test-suite` modules in the 2.6.x](https://github.com/micronaut-projects/micronaut-aws/pull/1217). test-suite modules appeared first in 2.6.x branch. I have merged up from `2.6.x` to `2.7.x`, `2.8.x`, `2.9.x` `3.0.x` and `master`

Should the following snippet had been present since we introduced the bom module: 

```groovy
if (p != project) {
      evaluationDependsOn(p.path)
}
```

**Comment by melix** [comment]
The `evaluationDependsOn` is needed because the BOM module directly accesses the other project's state (via `project.version`) which is unfortunately unsafe. Therefore it is possible that the `version` (or `group`) written in the BOM is `undefined` without it.

**Review by melix — APPROVED** [review]

**Comment by sdelamo** [comment]
@melix  this should have been applied since we introduced the `bom` submodule right?

**Comment by melix** [comment]
It is required as soon as you access another project's state directly. However, because of how Gradle evaluates `allprojects` and `subprojects`, it _may_ be that for builds which use this pattern, it works correctly. This is however undefined behavior, since there's no guarantee _when_ the closure will be called.

**Pull request merged**
