### PR TITLE
build: Gradle build plugin to 5.0.2 and set projectGroup

### PR DESCRIPTION
**Pull request by ilopmar**
This upgrades to 5.0.2 that fixes the snapshot publish

### CODE REVIEW

**Review by melix — APPROVED** [review]

**Comment by ilopmar** [comment]
I'll leave @sdelamo the final approve + merge so he is aware of the changes

**Review by sdelamo — CHANGES_REQUESTED** [review]
If I understand correctly, with 5.0.2 now version uses `projectVersion` in gradle.properties and `group` uses `projectGroup` in `gradle.properties`. 

If that it is correct, then I think modules should apply `io.micronaut.build.internal.module` not `io.micronaut.build.internal.aws-module.gradle`

**Comment by melix** [comment]
> If that it is correct, then I think modules should apply `io.micronaut.build.internal.module` not io.micronaut.build.internal.aws-module.gradle

There _can_ apply only the `io.micronaut.build.internal.module` plugin but there's no harm in keeping the `aws-module` plugin in case some common configuration shows up (this is what the project template actually says now: it has a convention plugin but explains you can remove it if there's no common configuration).

**Comment by sdelamo** [comment]
> > If that it is correct, then I think modules should apply `io.micronaut.build.internal.module` not io.micronaut.build.internal.aws-module.gradle
> 
> There _can_ apply only the `io.micronaut.build.internal.module` plugin but there's no harm in keeping the `aws-module` plugin in case some common configuration shows up (this is what the project template actually says now: it has a convention plugin but explains you can remove it if there's no common configuration).

In this PR, 

https://github.com/micronaut-projects/micronaut-problem-json/pull/80/files

We delete `problem-base`. 

I strongly believe that we have to do the same strategy in every module. 

I personally prefer to delete the base plugin if the only thing that it does is to apply `internal.module`.

**Comment by melix** [comment]
So objection from my side.

**Comment by sdelamo** [comment]
Why did you close the PR?. I still think we should use `projectGroup=io.micronaut.aws`and upgrade to 5.0.2

**Comment by melix** [comment]
Closing wasn't intentional at all. I don't even recall clicking a button :/

**Pull request merged**
